name: greenlist

version: 0.0.2+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  encrypt: ^3.3.1
  crypto: ^2.1.3
  dio: ^3.0.4
  flutter_svg: ^0.14.4
  cached_network_image: ^1.1.3
  flutter_bloc: ^2.0.0
  hydrated_bloc: ^2.0.0
  path_provider: ^1.4.2
  sembast: ^2.1.0+1
  page_transition: ^1.1.5
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.0.0
  shimmer: ^1.0.1
  uuid: ^2.0.1
  wave: ^0.0.8

flutter:
  fonts:
    - family:  NTR
      fonts:
       - asset: assets/NTR.ttf
  assets:
    - assets/kMarketLogo.svg
  uses-material-design: true